# Travis CI integration
# Defaults to GNU GCC and autotools: ./configure && make && make test
language: c

# We don't need to install packages, use dockerized build, quicker
sudo: false

compiler:
  - gcc

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "MWwMwXvJ8unp8gEbvysSsxC1x0bm1WGmewZcXreLI7OpKxDNoz9U8HBCuwnsX5r63HOl35lvgd0Ov8kFlGjDdSqYFyph/+U1zZEGpqi0RqICBrAHDx9YTO2uVB2xYBI38G6XVVLYdjq+Bv6B3JsxkWts9xB/e0l701iF4ViE3OFyxUJGPHnoShi/T+zHBeBuh8/JGwM4YCMVdyau6y0GR+t4701qI3BlQoEIl7J1ci1aXQnPyyrSfcdja4bzpfeM68B0dgERChWkHmfz+Hz5/EuVVbgFrI2CFWd3rmoZcZYMiiDFRbdoBjcEqRBKyxcZpCtN8LPogJHyKSRuG9EQDPAG2QZQ59iH5WRkWxGtTcvh/OkeX38uCajguxKviFyFQNMjF9xaYPo5HhP8wg48AOkPO+81keWFtwZ9JFXTTmD7DnC8z8/xaEUYLETv9Eqknpmg4Dxuvjszdwq627if98Dq5WNRpRxZ2iPx64PRk3SMnbnozNC4uYFJHbh9zW8gpJoEG4GL6XzW3P+JqqoKxZX1g56bCN8u4TA3rEQ2mxe8S2cQV/FwCeX9ZRX00SOv96x7VIkWi1fgLeQ4G7lKTjYb8U8/EeYkQdcNV0vLKGlhW/Ft0woK43+kPX4VT6bRcLg50c8TGl9PY+0IiOCaLEMExW1VxOkFDjx+W7s3vEw="

before_install:
  - echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  apt:
    packages:
      - tree
      - libconfuse-dev
      - libssl-dev
      - zlib1g-dev
  coverity_scan:
    project:
      name: "troglobit/merecat"
      description: "Simple HTTP/HTTPS server based on Jef Poskanzer's thttpd"
    notification_email: troglobit@gmail.com
    build_command_prepend: "./autogen.sh && ./configure"
    build_command: "make clean all"
    branch_pattern: dev

# We don't store generated files (configure and Makefile) in GIT,
# so we must customize the default build script to run ./autogen.sh
# Try first to build without SSL to check for regressions, then run
# all unit tests on a merecat with HTTPS enabled.
script:
  - ./autogen.sh
  - ./configure --prefix=/tmp --without-ssl --enable-htaccess --enable-htpasswd
  - make clean
  - make V=1 || cat config.h
  - make distclean
  - ./configure --prefix=/tmp
  - make V=1 || cat config.h
  - make install-strip
  - make check
  - tree /tmp
  - ldd /tmp/sbin/merecat
  - /tmp/sbin/merecat -h
