# Travis CI integration
# Defaults to GNU GCC and autotools: ./configure && make && make test
language: c

# We don't need to install packages, use dockerized build, quicker
sudo: false

compiler:
  - gcc

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "Da/XEtFs028XGQc7da9sJ0LuSt6rM1iFSWGIEzSXjEUSYLguMKQoiz8MiHCDHpgFXnt4d6ZVWWfjIc8RkawjHfIy7TmNTdvt8nXHapG26U2yZSHRUpgPi8fSQ13UKvtja5h16lnx8mfw+dR2rxbxgkwXZ/7a5+vjdAXkt9eVW5i90+ddp/nk/M6StcGCa9gxTFky9ulJohXVIUyQu0R0PEoc6YCOzMDwaXpRi3uZklwQ3mqm2tEw8nDeqHUEAE+uQRSk1yQWk4HAQesvlcLcydgdD72B3xNaiezAPCpEQV53RBaVd0DgeaMFpnu+6zzhnBekpRLJqaH2BQDNNqIJ84/DNrt+HulJ349M7YXQcIBaDZkBW/KoinhhlEvvlghCoLr91Qp5yjyStdcD8+b8xDzDn76mtne9QHOOLr4cWtWBwHdeqqFyqVLCfiYtyrUfgpKb+hOYWsDj+qfxRHZFLdu7EybXpt73d+iViOXhA5rXSywB7hki5KZ/joK0efIcCtUZoph3KEYkV0+FBo/R759C73wBkuVOngOKRUG2JX18jlFfrZsqDe9UU0L5VUjdX05fBObowZKXSQbs48AlVGxgQ9eXwQbQbo7rn+GxU0TtOVvPmSZLgkGQthv/3YxlMyTqa5aAm3iTWoWv7X/3A3n4HNMCvy2GyKjQIY7K9uQ="

before_install:
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  apt:
    packages:
      - tree
      - libconfuse-dev
      - libssl-dev
      - zlib1g-dev
  coverity_scan:
    project:
      name: "troglobit/merecat"
      description: "Simple HTTP/HTTPS server based on Jef Poskanzer's thttpd"
    notification_email: troglobit@gmail.com
    build_command_prepend: "./autogen.sh && ./configure"
    build_command: "make clean all"
    branch_pattern: dev

# We don't store generated files (configure and Makefile) in GIT,
# so we must customize the default build script to run ./autogen.sh
# Try first to build without SSL to check for regressions, then run
# all unit tests on a merecat with HTTPS enabled.
script:
  - ./autogen.sh
  - ./configure --prefix=/tmp --without-ssl --enable-htaccess --enable-htpasswd
  - make clean
  - make V=1 || cat config.h
  - make distclean
  - ./configure --prefix=/tmp
  - make V=1 || cat config.h
  - make install-strip
  - make check
  - tree /tmp
  - ldd /tmp/sbin/merecat
  - /tmp/sbin/merecat -h
