# Travis CI integration
# Defaults to GNU GCC and autotools: ./configure && make && make test
language: c

# We don't need to install packages, use dockerized build, quicker
sudo: false

compiler:
  - gcc
  - clang

addons:
  apt:
    packages:
      - tree
      - libconfuse-dev
      - libssl-dev

# We don't store generated files (configure and Makefile) in GIT,
# so we must customize the default build script to run ./autogen.sh
# Try first to build without SSL to check for regressions, then run
# all unit tests on a merecat with HTTPS enabled.
script:
  - ./autogen.sh
  - ./configure --prefix=/tmp --without-ssl
  - make V=1 || cat config.h
  - make distclean
  - ./configure --prefix=/tmp
  - make V=1 || cat config.h
  - make install-strip
  - make check
  - tree /tmp
  - ldd /tmp/sbin/merecat
  - /tmp/sbin/merecat -h
