# Travis CI integration
# Defaults to GNU GCC and autotools: ./configure && make && make test
language: c

# Ubuntu 18.04 LTS has OpenSSL 1.1, which is requried by Merecat httpd
dist: bionic

# Test build with both GCC and Clang (LLVM)
#  - clang
compiler:
  - gcc

# The secure: declaration is the encrypted COVERITY_SCAN_TOKEN, created
# using the "travis encrypt" command using the project repo's public key
env:
  global:
   - secure: "R/tA76hrmIOTEzcxIra7TqdLRGWHbEiVdKNcbISdHYodkPeeNvLuQLGFBfhJyatnepVO1xCQ8fOCSXmPJMIvrAL8BRIyI9cpYmEfJ4mRkg+WtY1SKsI1KPd3e3vlUErcbm1+J5Q2I7jJlnJ2hk/jOGjs+cAQIYAqv/UlklTZdy79oA2YvL03TFyVyBOLhdFDWOY+FrSBHHEwE4QxRPHOyDZCOxSJWMzvOozN+584PK+oY8Zqzj/JpCu1DUQsUL46m2feIRD4onHHBh4dUzX0bktm1OAhEU5GeX+wkfcVhF3HBDNpiORHklH8Ic0Wtm5CYqTXpTwkxV3GBKTlrlADmYaHA23qevAfV4Nh5jAAS1XLC8rJ4l+dmJ6BQqfJ6CXhcNqQLwLO7eC5ztWiUvIxARHv++R1R1dNoRtU73IsYt19TkwcDPTm9JgjyXrC9LOK1gpH6pzDoQU8zkYdEFKfvfQwnJkO1zfHzQMDnZ/nJgHqLPL6GWP/2JZ+tDIixuPZrKgMIwnUG7xW66fyxPw2S4kgsOAaVjchEINQoUN1q4xKm42u5VWvJNhdE7TMaOZF5BxxGy/xRecph0aV40PvtQTflfrtO92MQXZcROLBiYv/WtYYpasF0ZKTzVn0WrJZAfFoJWA+QFJR/6D7sU4P2hSVlnRir64sEv09DLlPzb8="

#  - sudo apt-get update
before_install:
  - sudo apt-get install -y tree libconfuse-dev libssl-dev zlib1g-dev
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

addons:
  coverity_scan:
    project:
      name: "troglobit/merecat"
      description: "Simple HTTP/HTTPS server based on Jef Poskanzer's thttpd"
    notification_email: troglobit@gmail.com
    build_command_prepend: "./autogen.sh && ./configure"
    build_command: "make clean all"
    branch_pattern: dev

# We don't store generated files (configure and Makefile) in GIT,
# so we must customize the default build script to run ./autogen.sh
# Try first to build without SSL to check for regressions, then run
# all unit tests on a merecat with HTTPS enabled.
script:
  - ./autogen.sh
  - ./configure --prefix=/ --without-ssl --enable-htaccess --enable-htpasswd
  - make clean
  - make V=1 || cat config.h
  - make clean
  - ./configure --prefix=/
  - make V=1 || cat config.h
  - make check
  - DESTDIR=/tmp/tok make install-strip
  - tree /tmp/tok
  - ldd /tmp/tok/sbin/merecat
  - /tmp/tok/sbin/merecat -h
