# Travis CI integration
# Defaults to GNU GCC and autotools: ./configure && make && make test
language: c

# Ubuntu 18.04 LTS has OpenSSL 1.1, which is requried by Merecat httpd
dist: bionic

# Test build with both GCC and Clang (LLVM)
#  - clang
compiler:
  - gcc

before_install:
  - sudo apt-get install -y tree libconfuse-dev libssl-dev zlib1g-dev

# We don't store generated files (configure and Makefile) in GIT,
# so we must customize the default build script to run ./autogen.sh
# Try first to build without SSL to check for regressions, then run
# all unit tests on a merecat with HTTPS enabled.
script:
  - ./autogen.sh
  - ./configure --prefix=/ --without-ssl --enable-htaccess --enable-htpasswd
  - make clean
  - make V=1 || cat config.h
  - make clean
  - ./configure --prefix=/
  - make V=1 || cat config.h
  - make check
  - DESTDIR=/tmp/tok make install-strip
  - tree /tmp/tok
  - ldd /tmp/tok/sbin/merecat
  - /tmp/tok/sbin/merecat -h
